SELECT * FROM USER_TABLES;

SELECT RAZ.NOMBRE AS "RAZA", ARQ.*, HAB.NOMBRE AS "RASGO"
FROM RAZAS RAZ
JOIN ARQUETIPOS ARQ ON RAZ.idArquetipo = ARQ.idArquetipo
JOIN RASGOS RAS ON RAZ.idRasgo = RAS.idHabilidad
JOIN HABILIDADES HAB ON RAS.idHabilidad = HAB.idHabilidad;

SELECT * FROM PERSONAJES;

SELECT * FROM RAZAS;
SELECT * FROM RELIGIONES;
SELECT * FROM REINOS;
SELECT * FROM IDEOLOGIAS;
SELECT * FROM CLASES;

SELECT * FROM CLASES;