SELECT * FROM USER_TABLES;

SELECT RAZ.NOMBRE AS "RAZA", ARQ.*, HAB.NOMBRE AS "RASGO"
FROM RAZAS RAZ
JOIN ARQUETIPOS ARQ ON RAZ.idArquetipo = ARQ.idArquetipo
JOIN RASGOS RAS ON RAZ.idRasgo = RAS.idHabilidad
JOIN HABILIDADES HAB ON RAS.idHabilidad = HAB.idHabilidad;

SELECT * FROM PERSONAJES;

SELECT * FROM MUNDO_NPC;
SELECT * FROM MUNDO_PERSONAJE;
SELECT * FROM MUNDO_CRIATURA;
SELECT * FROM TIENDA_OBJETOS;
SELECT * FROM INVENTARIO_PERSONAJE;
SELECT * FROM EQUIPO_PERSONAJE;

SELECT * FROM OBJETOS;
SELECT * FROM ARMADURAS;
SELECT * FROM NACIONES;
SELECT * FROM MUNDOS;
SELECT * FROM RAZAS;
SELECT * FROM RELIGIONES;
SELECT * FROM REINOS;
SELECT * FROM IDEOLOGIAS;
SELECT * FROM HABILIDADES;

SELECT * FROM ARQUETIPOS;
SELECT * FROM CLASES;
SELECT * FROM RASGOS;
SELECT * FROM CRIATURAS;
SELECT * FROM UBICACIONES;
SELECT * FROM TIENDAS;
SELECT * FROM ESCENAS;

SELECT * FROM O_NACIONES;
SELECT * FROM O_REINOS;